baseURL = 'https://example.org/'
languageCode = 'en-us'
paginate = 5
title = "John Doe"

[params]
author = "John Doe"
copyright = "John Doe"
subtitle = 'Senior Software Engineer'

  [[params.socialIcons]]
    icon = "bi-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/dillan-hildebrand-4762a4208/"

  [[params.socialIcons]]
    icon = "bi-github"
    title = "GitHub"
    url = "https://github.com/selftaught"


[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 15

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 30


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4